{"name": "test_update_users[NoValid- Book not found]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid book_id from Excel: 'None'", "trace": "self = <tests.test_api_resource.TestusersAPI object at 0x000001EAE8B34B50>, data = {'action': 'update_by_id', 'author': 'Nobody', 'book_id': 0.0, 'expected': False, ...}\n\n    @allure.description(\"Updates users details by users ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n    def test_update_users(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           book_id = extract_book_id(data, fallback_id=self.__class__.created_ids[0])\n\ntests\\test_api_resource.py:45: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = {'action': 'update_by_id', 'author': 'Nobody', 'book_id': 0.0, 'expected': False, ...}, fallback_id = 3\n\n    def extract_book_id(data, fallback_id):\n        \"\"\"\n        Extracts book_id from input data.\n        If missing or empty, uses fallback_id.\n        \"\"\"\n        raw = data.get(\"book_id\")\n>       return int(float(raw)) if str(raw).strip() else fallback_id\nE       TypeError: float() argument must be a string or a real number, not 'NoneType'\n\nutils\\input.py:16: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_resource.TestusersAPI object at 0x000001EAE8B34B50>, data = {'action': 'update_by_id', 'author': 'Nobody', 'book_id': 0.0, 'expected': False, ...}\n\n    @allure.description(\"Updates users details by users ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n    def test_update_users(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            book_id = extract_book_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid book_id from Excel: '{data.get('book_id')}'\")\nE           Failed: [ERROR] Invalid book_id from Excel: 'None'\n\ntests\\test_api_resource.py:47: Failed"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "6480795c-ce54-4f59-aef1-02ee1f15ce22-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "7140f066-13b5-4153-94e1-e51f565efd6e-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "e9d8e1a6-10fc-45c0-a52b-187ab33058df-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'book_id': 0.0, 'author': 'Nobody', 'is_borrowed': 0.0, 'title': 'Ghost Book', 'user': '', 'expected': False, 'note': 'NoValid- Book not found'}"}], "start": 1753272564134, "stop": 1753272564135, "uuid": "da6b1b68-acd6-4e41-be14-3dcd6d383a06", "historyId": "829b53ed9a6f6fed97fcf763401943e3", "testCaseId": "8f30c748a08cbeff2e9210952ed78284", "fullName": "tests.test_api_resource.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_resource"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "16692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_resource"}]}