{"name": "test_update_users[Valid-Partial Update]", "status": "failed", "statusDetails": {"message": "Failed: [ERROR] Invalid book_id from Excel: 'None'", "trace": "self = <tests.test_api_resource.TestusersAPI object at 0x0000026507B85350>, data = {'action': 'update_by_id', 'author': 'Only Author', 'book_id': '', 'expected': True, ...}\n\n    @allure.description(\"Updates users details by users ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n    def test_update_users(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n>           book_id = extract_book_id(data, fallback_id=self.__class__.created_ids[0])\n\ntests\\test_api_resource.py:45: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = {'action': 'update_by_id', 'author': 'Only Author', 'book_id': '', 'expected': True, ...}, fallback_id = 3\n\n    def extract_book_id(data, fallback_id):\n        \"\"\"\n        Extracts book_id from input data.\n        If missing or empty, uses fallback_id.\n        \"\"\"\n        raw = data.get(\"book_id\")\n>       return int(float(raw)) if str(raw).strip() else fallback_id\nE       TypeError: float() argument must be a string or a real number, not 'NoneType'\n\nutils\\input.py:16: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <tests.test_api_resource.TestusersAPI object at 0x0000026507B85350>, data = {'action': 'update_by_id', 'author': 'Only Author', 'book_id': '', 'expected': True, ...}\n\n    @allure.description(\"Updates users details by users ID.\")\n    @pytest.mark.parametrize(*load_test_data(\"apis\", \"update_by_id\", parametrize=True))\n    def test_update_users(self, data):\n        expected = parse_bool(data.get(\"expected\"))\n        try:\n            book_id = extract_book_id(data, fallback_id=self.__class__.created_ids[0])\n        except Exception:\n>           pytest.fail(f\"[ERROR] Invalid book_id from Excel: '{data.get('book_id')}'\")\nE           Failed: [ERROR] Invalid book_id from Excel: 'None'\n\ntests\\test_api_resource.py:47: Failed"}, "description": "Updates users details by users ID.", "attachments": [{"name": "‚è∞ Test Start Time", "source": "476547f0-da02-40e6-b4a0-4a9fc8f3c825-attachment.txt", "type": "text/plain"}, {"name": "üèÅ Test End Time", "source": "a3209a2f-e65d-4ac7-a571-6cbb588c1aa5-attachment.txt", "type": "text/plain"}, {"name": "‚è±Ô∏è Test Duration", "source": "2ca148d6-8ae8-4391-acc3-6ae2a202c0d6-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'action': 'update_by_id', 'book_id': '', 'author': 'Only Author', 'is_borrowed': '', 'title': 'Updated Title2', 'user': '', 'expected': True, 'note': 'Valid-Partial Update'}"}], "start": 1753272741036, "stop": 1753272741037, "uuid": "5d7e215c-8918-427e-bb1f-951c5582a473", "historyId": "a94f59ed388e8ad31514b6f0bae59cad", "testCaseId": "8f30c748a08cbeff2e9210952ed78284", "fullName": "tests.test_api_resource.TestusersAPI#test_update_users", "labels": [{"name": "epic", "value": "users API"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api_resource"}, {"name": "subSuite", "value": "TestusersAPI"}, {"name": "host", "value": "Saber"}, {"name": "thread", "value": "13616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api_resource"}]}